"""
Condition 1: You have the correct PIN.
Condition 2: You have enough money in your account.
Result: You get cash only if both Condition 1 AND Condition 2 are True
"""

# pin = 1234
# money = 50

# if pin == 1234 and 200 < money:
#     print("You get cash")
# else:
#     print("You do not get cash")
    
    

""" 
Smart Home Automation (Security Light)
Condition A: The backyard motion sensor triggers.
Condition B: The back door is opened.
Result: The security floodlight turns on if motion is detected OR if the door opens.
"""

# back_door_open = False
# motion_sensed = False

# if back_door_open or motion_sensed:
#     print("Security floodlight turns on")
# else:
#     print("False alert: Security floodlight remains off")



print(not False)